# Generated by Django 4.1.3 on 2022-11-22 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0008_alter_lessonrequest_is_available_on_friday_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonrequest",
            name="lesson_duration_in_mins",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="lessonrequest",
            name="lesson_interval_in_days",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="lessonrequest",
            name="no_of_lessons",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
