# Generated by Django 4.1.3 on 2022-11-23 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0009_alter_lessonrequest_lesson_duration_in_mins_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonrequest",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
