# Generated by Django 4.1.3 on 2022-11-23 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0012_alter_lessonrequest_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
