# Generated by Django 4.1.3 on 2022-11-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_alter_term_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
