# Generated by Django 4.1.3 on 2022-11-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0018_teacher_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_booking_finalised',
            field=models.BooleanField(default=False),
        ),
    ]
