# Generated by Django 4.1.3 on 2022-11-27 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0019_lesson_is_booking_finalised'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lessons.lessonrequest'),
        ),
    ]
