# Generated by Django 4.1.3 on 2022-11-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0021_alter_lesson_lesson_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_booking_finalised',
        ),
    ]
